#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_cLeonDecoy_Cube_1point0

#include "Basic.hpp"

#include "BP_cLeonDecoy_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_cLeonDecoy_Cube_1point0.BP_cLeonDecoy_Cube_1point0_C
// 0x0000 (0x02B8 - 0x02B8)
class ABP_cLeonDecoy_Cube_1point0_C final : public ABP_cLeonDecoy_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_cLeonDecoy_Cube_1point0_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_cLeonDecoy_Cube_1point0_C")
	}
	static class ABP_cLeonDecoy_Cube_1point0_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_cLeonDecoy_Cube_1point0_C>();
	}
};
DUMPER7_ASSERTS_ABP_cLeonDecoy_Cube_1point0_C;

SDK_NAMESPACE_END
