#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RandomObject_RandomMaterial

#include "Basic.hpp"

#include "BP_RandomObject_Base_classes.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_RandomObject_RandomMaterial.BP_RandomObject_RandomMaterial_C
// 0x0038 (0x02F0 - 0x02B8)
class ABP_RandomObject_RandomMaterial_C final : public ABP_RandomObject_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_RandomObject_RandomMaterial_C;   // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class UMaterialInstance*>              Materials;                                         // 0x02C0(0x0010)(Edit, BlueprintVisible)
	TArray<class AActor*>                         TargetActors;                                      // 0x02D0(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	int32                                         ElementIndex;                                      // 0x02E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRandomStream                          Seed;                                              // 0x02E4(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, RepNotify, NoDestructor)

public:
	void UserConstructionScript();
	void SpawnSet();
	void SetIndex(bool* Error);
	void ReceiveBeginPlay();
	void OnRep_Seed();
	void OnRep_CurrentIndex();
	void IndexUpdate();
	void ExecuteUbergraph_BP_RandomObject_RandomMaterial(int32 EntryPoint);
	void CheckLoop();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RandomObject_RandomMaterial_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RandomObject_RandomMaterial_C")
	}
	static class ABP_RandomObject_RandomMaterial_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RandomObject_RandomMaterial_C>();
	}
};
DUMPER7_ASSERTS_ABP_RandomObject_RandomMaterial_C;

SDK_NAMESPACE_END
