#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: cLeon_game

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function cLeon_game.cLeon_game_C.ExecuteUbergraph_cLeon_game
// 0x0004 (0x0004 - 0x0000)
struct cLeon_game_C_ExecuteUbergraph_cLeon_game final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_cLeon_game_C_ExecuteUbergraph_cLeon_game;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
