#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BoolSwitcher

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UINavigation_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BoolSwitcher.WBP_BoolSwitcher_C
// 0x0040 (0x0950 - 0x0910)
class UWBP_BoolSwitcher_C final : public UUINavComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0910(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Border_61;                                         // 0x0918(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTexture2D*                             Active;                                            // 0x0920(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             Deactive;                                          // 0x0928(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          CheckState;                                        // 0x0930(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_931[0x7];                                      // 0x0931(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(bool Value)>    ChangeValue;                                       // 0x0938(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ToggleCheckState();
	void SetCheckState(bool CheckState);
	void PreConstruct(bool IsDesignTime_PreConstruct);
	void ExecuteUbergraph_WBP_BoolSwitcher(int32 EntryPoint);
	void BndEvt__WBP_BoolSwitcher_NavButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BoolSwitcher_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BoolSwitcher_C")
	}
	static class UWBP_BoolSwitcher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BoolSwitcher_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BoolSwitcher_C;

SDK_NAMESPACE_END
